# Generated by Django 5.2.6 on 2025-09-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Sepatu'), ('ball', 'Bola'), ('merch', 'Merchandise')], default='jersey', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('brand', models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('puma', 'Puma'), ('under_armour', 'Under Armour'), ('reebok', 'Reebok')], default='adidas', max_length=50)),
            ],
        ),
    ]
